= PM2005 Laser Particle Sensor Module Library for Arduino =

This is a library for the laser particle sensor module PM2005 manufactured
by Wuhan Cubic Optoelectronics. The PM2005 module counts airborne particles
of different sizes in catagories of 0.3, 2.5, and 10 micrometres, and
measures their concentrations in units of particles/liter. The PM2005 module also
estimates the Particulate Matter level (PM level) of fine particles (PM2.5)
and coarse particles (PM10) in units of microgram/cubic meter.

To get started on a project quickly you can use Arduino, or also the
"PM2005 TestKit" (PM2005, USB/serial converter, example readout program for Windows)
that is sold by Diwell.

This library provides control and easy read-out of PM2005 module measurements.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/PM2005ParticleSensor

For a similar sensor see DFRobot SKU:SEN0177 with a sensor module by Insan.
Note the SKU:SEN0177 apparently does not work with Arduino software serial.

Interfacing PM2005 and Arduino is easy, though no Arduino Shield is available.
The PM2005 needs 4 wires (GND, 5V, RX, TX). A good 5V supply of between 4.9V
and 5.1V is necessary. With an only USB-powered Arduino Nano, the Nano 5V pin
output is 4.7V, which is too low for solid operation of the PM2005. It is thus
advisable to supply even an USB-attached Arduino Nano with external power.

== License ==

Copyright (c) 2011-2014 Arduino LLC. All right reserved.
Copyright (C) 2006-2008, Atmel Corporation All rights reserved.
Copyright (c) 2001-2004 Swedish Institute of Computer Science.
Copyright (c) 2009-2010, H&D Wireless AB All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
