= PM2005 Laser Particle Sensor Module Library for Arduino =

The laser particle sensor module PM2005 by Wuhan Cubic Optoelectronics
measures dust concentrations (pcs/liter) by counting airborne particles
of different size (0.3 micrometres, 2.5 micrometres, 10 micrometres).

It also reports estimates of the Particulate Matter level (PM level)
for fine particles (PM2.5; 2.5 micrometres) and for coarse particles (PM10;
10 micrometres) in units of microgram/cubic meter.

The company Diwell sells a "PM2005 TestKit" (PM2005, USB/serial converter,
example readout program for Windows) for fast initial testing.

This library provides PM2005 control and easy read-out of measurements.

Interfacing PM2005 to an Arduino is easy, even though there is no Arduino
Shield available. The PM2005 needs 4 wires: GND, +5V, and serial RX and TX
either from an Arduino hardware or a software serial port. The module needs
a good +5V supply (the voltage should be 5.0+-0.1V). For example on the
Arduino Nano the pin +5V output is too low (4.5V typical).

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/PM2005ParticleSensor

For a similar sensor see DFRobot SKU:SEN0177 with a sensor module by Insan.
Note the SKU:SEN0177 apparently does not work with Arduino software serial.

== License ==

Copyright (c) 2011-2014 Arduino LLC. All right reserved.
Copyright (C) 2006-2008, Atmel Corporation All rights reserved.
Copyright (c) 2001-2004 Swedish Institute of Computer Science.
Copyright (c) 2009-2010, H&D Wireless AB All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
